// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVFRQRnFIQKZdeHa6ZzcFNr3tdGwa_RJU',
    appId: '1:480320484869:web:7a0f7bef6be5ade2e28e6c',
    messagingSenderId: '480320484869',
    projectId: 'fastcampus-market-02',
    authDomain: 'fastcampus-market-02.firebaseapp.com',
    storageBucket: 'fastcampus-market-02.appspot.com',
    measurementId: 'G-7C6W9FHGWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPyH-7Ce1-LvlL2wNB_te3BfJbyX8rg6I',
    appId: '1:480320484869:android:168cfbbce6a35330e28e6c',
    messagingSenderId: '480320484869',
    projectId: 'fastcampus-market-02',
    storageBucket: 'fastcampus-market-02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrzFzjyokhW41CMLo5HiBRYO7WljGGOkU',
    appId: '1:480320484869:ios:8ddec416c00df5aee28e6c',
    messagingSenderId: '480320484869',
    projectId: 'fastcampus-market-02',
    storageBucket: 'fastcampus-market-02.appspot.com',
    iosClientId: '480320484869-jm26fjjk9ckru2rpg3r5aqqad145ueeb.apps.googleusercontent.com',
    iosBundleId: 'com.archy712.fastcampusMarket02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrzFzjyokhW41CMLo5HiBRYO7WljGGOkU',
    appId: '1:480320484869:ios:8ddec416c00df5aee28e6c',
    messagingSenderId: '480320484869',
    projectId: 'fastcampus-market-02',
    storageBucket: 'fastcampus-market-02.appspot.com',
    iosClientId: '480320484869-jm26fjjk9ckru2rpg3r5aqqad145ueeb.apps.googleusercontent.com',
    iosBundleId: 'com.archy712.fastcampusMarket02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVFRQRnFIQKZdeHa6ZzcFNr3tdGwa_RJU',
    appId: '1:480320484869:web:1bf072acab995058e28e6c',
    messagingSenderId: '480320484869',
    projectId: 'fastcampus-market-02',
    authDomain: 'fastcampus-market-02.firebaseapp.com',
    storageBucket: 'fastcampus-market-02.appspot.com',
    measurementId: 'G-9GTB2BZD8K',
  );
}
